# Identificador único e organização no SonarCloud /SonarQube
sonar.projectKey=backend
sonar.organization=your-organization-key
sonar.projectName=Backend API Monorepo

# URL do serviço (https://sonarcloud.io para SonarCloud ou http://localhost:9000 para SonarQube)
sonar.host.url=https://sonarcloud.io

# Diretório que contém o código-fonte a ser analisado
sonar.sources=src

# Diretório e padrões de arquivos de testes
sonar.tests=src/test
sonar.test.inclusions=**/*Test.ts,src/*Tests.ts,**/*.spec.ts

# Caminho do relatório de cobertura no formato LCOV (gerado pelo Vitest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# PASTAS E ARQUIVOS A SEREM IGNORADOS NA ANÁLISE
# Ignorar arquivos de configuração, scripts e arquivos de teste
sonar.exclusions=coverage/**,**/*.config.js,**/*.spec.ts,**/*.test.ts,**/tests/**,**/node_modules/**,**/dist/**
